name: transaction_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0 
  cloud_firestore:
  shared_preferences: ^2.2.2
  json_annotation: ^4.7.0
  fl_chart:
  flutter_easyloading: 
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter_redux: ^0.10.0
  freezed_annotation:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.0.5
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
